export const cookie = [
    {
        "domain": ".weibo.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "_s_tentry",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "login.sina.com.cn",
        "id": 1
    },
    {
        "domain": ".weibo.com",
        "expirationDate": 1636552249.271508,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ALF",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1636552249",
        "id": 2
    },
    {
        "domain": ".weibo.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "Apache",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "2048484170222.3179.1604842705161",
        "id": 3
    },
    {
        "domain": ".weibo.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "cross_origin_proto",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "SSL",
        "id": 4
    },
    {
        "domain": ".weibo.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "login_sid_t",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "a9c4852955cbb2f65f7fbc4f15686c82",
        "id": 5
    },
    {
        "domain": ".weibo.com",
        "expirationDate": 1919997397,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SINAGLOBAL",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "2934184934329.9.1604637397541",
        "id": 6
    },
    {
        "domain": ".weibo.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "SSOLoginState",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": "0",
        "value": "1605016249",
        "id": 7
    },
    {
        "domain": ".weibo.com",
        "hostOnly": false,
        "httpOnly": true,
        "name": "SUB",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": "0",
        "value": "_2A25yrurpDeRhGeNK7loT8yzMzziIHXVR2lshrDV8PUNbmtAKLVrwkW9NSTuviIlWNEhof1XlZNTMYjq9dmGxnbkQ",
        "id": 8
    },
    {
        "domain": ".weibo.com",
        "expirationDate": 1636552249.271218,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SUBP",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "0033WrSXqPxfM725Ws9jqgMF55529P9D9Whduy0DzFpqD35hZkbuuNkv5JpX5KzhUgL.Fo-XSKnEe0z7ShB2dJLoIcQLxK-LBK-LBKzLxKBLB.-L1hnLxK-L1KeL1h2LxK-L12-L1-qLxK-L12BL1K-LxK-L12eL1h-LxK-L12eL1h-LxK.LBK-LBo5LxK-L1KeL1h2LxKqL1h.L12zLxKnLBK2LBKyRqcj7S05N",
        "id": 9
    },
    {
        "domain": ".weibo.com",
        "expirationDate": 1635946705,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ULV",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1604842705175:2:2:1:2048484170222.3179.1604842705161:1604637397552",
        "id": 10
    },
    {
        "domain": ".weibo.com",
        "expirationDate": 1636378705,
        "hostOnly": false,
        "httpOnly": false,
        "name": "UOR",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": ",,www.google.com",
        "id": 11
    },
    {
        "domain": ".weibo.com",
        "expirationDate": 1605102655,
        "hostOnly": false,
        "httpOnly": false,
        "name": "webim_unReadCount",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "%7B%22time%22%3A1605016255869%2C%22dm_pub_total%22%3A162%2C%22chat_group_client%22%3A0%2C%22chat_group_notice%22%3A0%2C%22allcountNum%22%3A162%2C%22msgbox%22%3A0%7D",
        "id": 12
    },
    {
        "domain": "weibo.com",
        "expirationDate": 1605023815,
        "hostOnly": true,
        "httpOnly": false,
        "name": "wb_view_log_5458232044",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1707*9601.5",
        "id": 13
    },
    {
        "domain": "weibo.com",
        "hostOnly": true,
        "httpOnly": false,
        "name": "WBtopGlobal_register_version",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "2020111021",
        "id": 14
    }
    ]